import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Web3Modal from 'web3modal';
import WalletConnectProvider from '@walletconnect/web3-provider';
import {useEffect , useState} from 'react';
import { ethers } from 'ethers';
import ConnectBttn from '../components/ConnectBttn';
import { useAccount, useConnect, useDisconnect } from 'wagmi'
import { useSigner, useContract } from 'wagmi'
import {
 
  SchoolCrowdSale_ADDR,
  SchoolCrowdSale_ABI,
} from "../constants";

export default function Home() {

  const [isConnected, setIsConnected] = useState(false);

  // const contractConfig: UseContractConfig = {
  //   addressOrName: CreateBondandAdminRole_CONTRACT_ADDRESS,
  //   contractInterface: CreateBondandAdminRole_CONTRACT_ABI
  // }
  
  const { data: signer, isError, isLoading } = useSigner()
  const contract= useContract({
    
    address: SchoolCrowdSale_ADDR,
    abi: SchoolCrowdSale_ABI,
    functionName: "Mint",
  
  })

  const MintToken = () =>{
    console.log('Minted')
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Scholarship App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      
      <main className={styles.main}>
      <div>
             <ConnectBttn />
      </div>
        <h1 className={styles.title}>
          Welcome to <a href="/">SchoolCrowdSale App--</a>
        </h1>

        <p className={styles.description}>
          Dapp(beta) built for Chainlink hackathon 2022 {' '}


          {/*<code className={styles.code}>pages/index.tsx</code>*/}
        </p>

        <div className={styles.grid}>
          

        <button id="Mint" onClick={()=>MintToken()}>MintToken</button>



        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
function greetUser() {
  throw new Error('Function not implemented.');
}

