import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Web3Modal from 'web3modal';
import WalletConnectProvider from '@walletconnect/web3-provider';
import {useEffect , useState} from 'react';
import { ethers } from 'ethers';

let web3Modal: Web3Modal;
const providerOptions = {
  walletconnect: {
    package: WalletConnectProvider,
    options: {
      rpc: { 42: ""},
    },
  },
};
export default function Home() {

  const [isConnected, setIsConnected] = useState(false);
  const [walletAddress, setWalletAddress] = useState<any>(null);
  
  const [provider, setProvider] = useState();
  const [library, setLibrary] = useState<any>(null);
  const [account, setAccount] = useState<any>();
  const [network, setNetwork] = useState<any>();
  
 
  const [examCount, setexamCount] = useState<any>(5);

async function connect() {
    try{
      console.log('connect method')
      const web3ModalProvider = await web3Modal.connect();
      console.log('accounts method') 
      const library = new ethers.providers.Web3Provider((web3ModalProvider as any));
       
       setProvider(web3ModalProvider);
       setLibrary(library);
       
    const accounts = await library.listAccounts();
    const network = await library.getNetwork();
    setProvider(provider);
    setLibrary(library);
    if (accounts) {
      setAccount(accounts[0]);
      setWalletAddress(accounts[0]);
      console.log(`account found : ${accounts[0]}`);
      return greetUser();
    } else{
      console.log('no accounts found');
    }
    
      
      // setWalletAddress(await signer.getAddress());
    } catch(e){
      console.log(`connect()-->${e}`);
    }
  }
  
  
    const renderNotConnectedContainer = () => (
    <button
      className="cta-button connect-wallet-button"
      onClick={connect}
    >
      Connect your wallet
    </button>
  );
  return (
    <div className={styles.container}>
      <Head>
        <title>Scholarship App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
             {renderNotConnectedContainer()}
            </div>
      <br></br>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="">Scholarship App</a>
        </h1>

        <p className={styles.description}>
          Dapp(beta) built for Chainlink hackathon 2022 {' '}


          {/*<code className={styles.code}>pages/index.tsx</code>*/}
        </p>

        <div className={styles.grid}>
          

          <a href="/donatePage" className={styles.card}>
            <h2>Donate &rarr;</h2>
            <p>Donors can donate to liquidity pool!</p>
          </a>

          <a href="/studentLogin" className={styles.card}>
            <h2>Student &rarr;</h2>
            <p>Student -take exam</p>
          </a>

          <a
            href="/proctorLogin"
            className={styles.card}
          >
            <h2>Proctor &rarr;</h2>
            <p>Conduct's Exam & contributes qns </p>
          </a>

          <a
            href="/"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Available Funds &rarr;</h2>
            <p>
              check available funds (not ready)
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
function greetUser() {
  throw new Error('Function not implemented.');
}

